# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_random"
version = "0.1.0"
license = "MIT"
author = ["John S. Urban"]
maintainer = "urbanjost@comcast.com"
copyright = "Copyright 2021, John S. Urban"
description = "pseudorandom generators"
categories = ["random"]
keywords = ["random", "pseudorandom", "fortran", "rng", "random-number-generator" ]
homepage = "https://github.com/urbanjost/M_random.git"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = true

[install]
library = false

[[executable]]
name="rand"
source-dir="app"
main="rand.f90"

[[executable]]
name="xauth_key"
source-dir="app"
main="xauth_key.f90"

[executable.dependencies]
M_io       =  {  namespace = "GPF" }
M_strings  =  {  namespace = "GPF" }
M_kracken  =  {  namespace = "GPF" }

#[[test]]
#name="test_suite"
#source-dir="test"
#main="test_suite_M_random.f90"

[test.dependencies]
M_framework = {namespace = "GPF"}
